"""RBI DBIE Sector-Mapped Registry & Thematic Data Catalog.
Source: Reserve Bank Innovation Hub (RBI DBIE)
Data API: https://data-api.dbie.rbihub.in
Official Themes: Banking, Prices, Markets, Government, External, Growth, Payments, Agriculture, Labour.
Each table is strictly mapped to its single-source-of-truth macroeconomic sector agent.
"""
from __future__ import annotations

from typing import Any, Dict, List

# Official DBIE Themes mapped to Macrograph Sectors
DBIE_THEMES: List[Dict[str, str]] = [
    {"key": "banking", "label": "Banking & Money", "sector": "finance_sector", "desc": "SCB Credit, Deposits, M3 Money Stock & Solvency"},
    {"key": "monetary", "label": "Monetary Policy & Liquidity", "sector": "monetary_sector", "desc": "Policy Repo Rate, SDF, Reserve Money & LAF"},
    {"key": "prices", "label": "Prices & Inflation", "sector": "prices_sector", "desc": "CPI Combined, WPI All Commodities, Food Inflation"},
    {"key": "markets", "label": "Financial Markets & Rates", "sector": "capital_market_sector", "desc": "Sovereign G-Sec Yields, Call Money & FPI Flows"},
    {"key": "government", "label": "Government & Fiscal", "sector": "fiscal_sector", "desc": "Union Receipts, Capital Outlay & Fiscal Deficit"},
    {"key": "external", "label": "External & Forex", "sector": "external_sector", "desc": "Forex Reserves, USD/INR Reference & Trade Balance"},
    {"key": "growth", "label": "Real Growth & Output", "sector": "real_sector", "desc": "GDP/GVA Growth, IIP & 8-Core Industries"},
    {"key": "payments", "label": "Digital Payments & Services", "sector": "services_sector", "desc": "UPI Volumes, NEFT/RTGS Settlements & Turnover"},
    {"key": "labour", "label": "Labour & Employment", "sector": "labour_sector", "desc": "PLFS Unemployment, Workforce & EPFO Payroll"},
    {"key": "agriculture", "label": "Agriculture & Rural", "sector": "agriculture_sector", "desc": "Crop Production, Buffer Stocks & Mandi Prices"},
]

# Canonical 10 Sector-mapped RBI DBIE tables with historical series for charting
SECTOR_DBIE_TABLES: Dict[str, List[Dict[str, Any]]] = {
    "finance": [
        {
            "id": "scb_credit_rn",
            "schema": "financial_sector",
            "table": "scb_credit_rn",
            "title": "Scheduled Commercial Banks Credit Deployment",
            "theme": "Banking",
            "sector": "finance_sector",
            "sector_name": "Finance & Banking",
            "dbie_path": "Banking > Scheduled Commercial Banks > Credit Deployment",
            "frequency": "Fortnightly",
            "unit": "₹ Lakh Crore",
            "latest_period": "2024-03-22",
            "latest_value": 164.35,
            "yoy_change": "+15.3%",
            "rows_count": 4820,
            "series": [
                {"period": "2023-03", "value": 136.75, "label": "Credit Deployment"},
                {"period": "2023-06", "value": 143.92, "label": "Credit Deployment"},
                {"period": "2023-09", "value": 151.27, "label": "Credit Deployment"},
                {"period": "2023-12", "value": 157.43, "label": "Credit Deployment"},
                {"period": "2024-03", "value": 164.35, "label": "Credit Deployment"},
            ],
            "table_data": [
                {"period": "2024-03-22", "value": 164.35, "yoy": "+15.3%", "component": "Gross Bank Credit", "status": "Final"},
                {"2023-12-29": "2023-12-29", "period": "2023-12-29", "value": 157.43, "yoy": "+15.8%", "component": "Gross Bank Credit", "status": "Final"},
                {"period": "2023-09-22", "value": 151.27, "yoy": "+15.1%", "component": "Gross Bank Credit", "status": "Final"},
                {"period": "2023-06-30", "value": 143.92, "yoy": "+16.2%", "component": "Gross Bank Credit", "status": "Final"},
            ],
            "citation": "RBI DBIE / DBIE Table scb_credit_rn (Fortnightly)",
            "mcp_command": 'get_series(table="scb_credit_rn")',
        },
        {
            "id": "npa_scb_rn",
            "schema": "financial_sector",
            "table": "npa_scb_rn",
            "title": "Asset Quality & Gross Non-Performing Assets of SCBs",
            "theme": "Banking",
            "sector": "finance_sector",
            "sector_name": "Finance & Banking",
            "dbie_path": "Banking > Financial Soundness Indicators > Asset Quality",
            "frequency": "Quarterly",
            "unit": "% of Gross Advances",
            "latest_period": "2024-03-31",
            "latest_value": 2.80,
            "yoy_change": "-110 bps",
            "rows_count": 1420,
            "series": [
                {"period": "2021-03", "value": 7.30, "label": "Gross NPA %"},
                {"period": "2022-03", "value": 5.80, "label": "Gross NPA %"},
                {"period": "2023-03", "value": 3.90, "label": "Gross NPA %"},
                {"period": "2023-09", "value": 3.20, "label": "Gross NPA %"},
                {"period": "2024-03", "value": 2.80, "label": "Gross NPA %"},
            ],
            "table_data": [
                {"period": "2024-03-31", "value": 2.80, "yoy": "-110 bps", "component": "SCB GNPA Ratio", "status": "Final"},
                {"period": "2023-09-30", "value": 3.20, "yoy": "-180 bps", "component": "SCB GNPA Ratio", "status": "Final"},
                {"period": "2023-03-31", "value": 3.90, "yoy": "-190 bps", "component": "SCB GNPA Ratio", "status": "Final"},
                {"period": "2022-03-31", "value": 5.80, "yoy": "-150 bps", "component": "SCB GNPA Ratio", "status": "Final"},
            ],
            "citation": "RBI DBIE / DBIE Table npa_scb_rn (Quarterly FSR)",
            "mcp_command": 'get_series(table="npa_scb_rn")',
        },
        {
            "id": "dep_cred_rn",
            "schema": "financial_sector",
            "table": "dep_cred_rn",
            "title": "Commercial Bank Deposits & Credit-Deposit (CD) Ratio",
            "theme": "Banking",
            "sector": "finance_sector",
            "sector_name": "Finance & Banking",
            "dbie_path": "Banking > Deposits & Credit > Aggregate Position",
            "frequency": "Fortnightly",
            "unit": "₹ Lakh Crore",
            "latest_period": "2024-03-22",
            "latest_value": 204.80,
            "yoy_change": "+13.5%",
            "rows_count": 3100,
            "series": [
                {"period": "2023-03", "value": 180.40, "label": "Aggregate Deposits"},
                {"period": "2023-06", "value": 187.20, "label": "Aggregate Deposits"},
                {"period": "2023-09", "value": 192.80, "label": "Aggregate Deposits"},
                {"period": "2023-12", "value": 198.50, "label": "Aggregate Deposits"},
                {"period": "2024-03", "value": 204.80, "label": "Aggregate Deposits"},
            ],
            "table_data": [
                {"period": "2024-03-22", "value": 204.80, "yoy": "+13.5%", "component": "SCB Aggregate Deposits", "status": "Final"},
                {"period": "2023-12-29", "value": 198.50, "yoy": "+13.1%", "component": "SCB Aggregate Deposits", "status": "Final"},
                {"period": "2023-09-22", "value": 192.80, "yoy": "+12.8%", "component": "SCB Aggregate Deposits", "status": "Final"},
            ],
            "citation": "RBI DBIE / DBIE Table dep_cred_rn",
            "mcp_command": 'get_series(table="dep_cred_rn")',
        },
    ],
    "monetary": [
        {
            "id": "bmc_m_rn",
            "schema": "financial_sector",
            "table": "bmc_m_rn",
            "title": "Broad Money Components (M3 Aggregates & Currency)",
            "theme": "Monetary",
            "sector": "monetary_sector",
            "sector_name": "Monetary & Liquidity",
            "dbie_path": "Money Stock > Components of Broad Money",
            "frequency": "Monthly",
            "unit": "₹ Lakh Crore",
            "latest_period": "2024-01-31",
            "latest_value": 243.01,
            "yoy_change": "+11.2%",
            "rows_count": 2770,
            "series": [
                {"period": "2023-06", "value": 231.10, "label": "Broad Money M3"},
                {"period": "2023-09", "value": 234.12, "label": "Broad Money M3"},
                {"period": "2023-11", "value": 236.85, "label": "Broad Money M3"},
                {"period": "2024-01", "value": 240.10, "label": "Broad Money M3"},
                {"period": "2024-03", "value": 243.01, "label": "Broad Money M3"},
            ],
            "table_data": [
                {"period": "2024-03-31", "value": 243.01, "yoy": "+11.2%", "component": "M3 Broad Money", "status": "Final"},
                {"period": "2024-01-31", "value": 240.10, "yoy": "+11.0%", "component": "M3 Broad Money", "status": "Final"},
                {"period": "2023-11-30", "value": 236.85, "yoy": "+10.8%", "component": "M3 Broad Money", "status": "Final"},
                {"period": "2023-09-30", "value": 234.12, "yoy": "+10.6%", "component": "M3 Broad Money", "status": "Final"},
            ],
            "citation": "RBI DBIE / DBIE Table bmc_m_rn (Monthly SDMX)",
            "mcp_command": 'get_series(table="bmc_m_rn")',
        },
        {
            "id": "policy_rates_rn",
            "schema": "financial_markets",
            "table": "policy_rates_rn",
            "title": "Policy Corridor: Policy Repo, SDF, MSF and Bank Rate",
            "theme": "Monetary",
            "sector": "monetary_sector",
            "sector_name": "Monetary & Liquidity",
            "dbie_path": "Financial Markets > Policy Rates > Liquidity Corridor",
            "frequency": "Bi-Monthly MPC",
            "unit": "% per annum",
            "latest_period": "2024-10-09",
            "latest_value": 6.50,
            "yoy_change": "0 bps (Neutral)",
            "rows_count": 480,
            "series": [
                {"period": "2022-05", "value": 4.40, "label": "Policy Repo Rate"},
                {"period": "2022-08", "value": 5.40, "label": "Policy Repo Rate"},
                {"period": "2022-12", "value": 6.25, "label": "Policy Repo Rate"},
                {"period": "2023-02", "value": 6.50, "label": "Policy Repo Rate"},
                {"period": "2024-10", "value": 6.50, "label": "Policy Repo Rate"},
            ],
            "table_data": [
                {"period": "2024-10-09", "value": 6.50, "yoy": "0 bps", "component": "Policy Repo Rate", "status": "Active"},
                {"period": "2024-10-09", "value": 6.25, "yoy": "0 bps", "component": "Standing Deposit Facility", "status": "Active"},
                {"period": "2024-10-09", "value": 6.75, "yoy": "0 bps", "component": "Marginal Standing Facility", "status": "Active"},
            ],
            "citation": "Monetary Policy Committee / RBI DBIE policy_rates_rn",
            "mcp_command": 'get_series(table="policy_rates_rn")',
        },
    ],
    "prices": [
        {
            "id": "cpi_ruc_rn",
            "schema": "real_sector",
            "table": "cpi_ruc_rn",
            "title": "Consumer Price Index (Rural, Urban, Combined) 2012=100",
            "theme": "Prices",
            "sector": "prices_sector",
            "sector_name": "Prices & Inflation",
            "dbie_path": "Prices > Consumer Price Index > CPI Combined",
            "frequency": "Monthly",
            "unit": "% YoY",
            "latest_period": "2024-08-31",
            "latest_value": 3.65,
            "yoy_change": "-320 bps",
            "rows_count": 16500,
            "series": [
                {"period": "2023-07", "value": 7.44, "label": "CPI Headline YoY"},
                {"period": "2023-10", "value": 4.87, "label": "CPI Headline YoY"},
                {"period": "2024-01", "value": 5.10, "label": "CPI Headline YoY"},
                {"period": "2024-04", "value": 4.83, "label": "CPI Headline YoY"},
                {"period": "2024-07", "value": 3.60, "label": "CPI Headline YoY"},
                {"period": "2024-08", "value": 3.65, "label": "CPI Headline YoY"},
            ],
            "table_data": [
                {"period": "2024-08-31", "value": 3.65, "yoy": "-320 bps", "component": "CPI Combined (Headline)", "status": "Final"},
                {"period": "2024-07-31", "value": 3.60, "yoy": "-384 bps", "component": "CPI Combined (Headline)", "status": "Final"},
                {"period": "2024-04-30", "value": 4.83, "yoy": "+13 bps", "component": "CPI Combined (Headline)", "status": "Final"},
                {"period": "2024-01-31", "value": 5.10, "yoy": "-62 bps", "component": "CPI Combined (Headline)", "status": "Final"},
            ],
            "citation": "National Statistical Office (NSO) / RBI DBIE cpi_ruc_rn",
            "mcp_command": 'get_series(table="cpi_ruc_rn")',
        },
        {
            "id": "wpi_all_rn",
            "schema": "real_sector",
            "table": "wpi_all_rn",
            "title": "Wholesale Price Index (All Commodities) 2011-12=100",
            "theme": "Prices",
            "sector": "prices_sector",
            "sector_name": "Prices & Inflation",
            "dbie_path": "Prices > Wholesale Price Index > All Commodities",
            "frequency": "Monthly",
            "unit": "% YoY",
            "latest_period": "2024-08-31",
            "latest_value": 1.31,
            "yoy_change": "+177 bps",
            "rows_count": 8900,
            "series": [
                {"period": "2023-08", "value": -0.46, "label": "WPI YoY"},
                {"period": "2023-11", "value": 0.39, "label": "WPI YoY"},
                {"period": "2024-02", "value": 0.20, "label": "WPI YoY"},
                {"period": "2024-05", "value": 2.61, "label": "WPI YoY"},
                {"period": "2024-08", "value": 1.31, "label": "WPI YoY"},
            ],
            "table_data": [
                {"period": "2024-08-31", "value": 1.31, "yoy": "+177 bps", "component": "WPI All Commodities", "status": "Final"},
                {"period": "2024-05-31", "value": 2.61, "yoy": "+609 bps", "component": "WPI All Commodities", "status": "Final"},
                {"period": "2024-02-29", "value": 0.20, "yoy": "-365 bps", "component": "WPI All Commodities", "status": "Final"},
            ],
            "citation": "Office of Economic Adviser / RBI DBIE wpi_all_rn",
            "mcp_command": 'get_series(table="wpi_all_rn")',
        },
    ],
    "fiscal": [
        {
            "id": "cg_exp_rn",
            "schema": "public_finance",
            "table": "cg_exp_rn",
            "title": "Central Government Revenue & Capital Expenditure",
            "theme": "Government",
            "sector": "fiscal_sector",
            "sector_name": "Fiscal & Union Budget",
            "dbie_path": "Public Finance > Central Government Accounts > Expenditure",
            "frequency": "Monthly",
            "unit": "₹ Lakh Crore",
            "latest_period": "2024-02-29",
            "latest_value": 37.47,
            "yoy_change": "+7.4%",
            "rows_count": 1840,
            "series": [
                {"period": "2023-06", "value": 10.50, "label": "Cumulative Expenditure"},
                {"period": "2023-09", "value": 18.52, "label": "Cumulative Expenditure"},
                {"period": "2023-12", "value": 28.11, "label": "Cumulative Expenditure"},
                {"period": "2024-02", "value": 37.47, "label": "Cumulative Expenditure"},
            ],
            "table_data": [
                {"period": "2024-02-29", "value": 37.47, "yoy": "+7.4%", "component": "Total Union Expenditure", "status": "Final"},
                {"period": "2023-12-31", "value": 28.11, "yoy": "+6.8%", "component": "Total Union Expenditure", "status": "Final"},
                {"period": "2023-09-30", "value": 18.52, "yoy": "+8.2%", "component": "Total Union Expenditure", "status": "Final"},
            ],
            "citation": "Controller General of Accounts / RBI DBIE Table cg_exp_rn",
            "mcp_command": 'get_series(table="cg_exp_rn")',
        },
        {
            "id": "cg_rcpt_rn",
            "schema": "public_finance",
            "table": "cg_rcpt_rn",
            "title": "Gross Tax Receipts and Devolution to States",
            "theme": "Government",
            "sector": "fiscal_sector",
            "sector_name": "Fiscal & Union Budget",
            "dbie_path": "Public Finance > Central Government Accounts > Tax Revenue",
            "frequency": "Monthly",
            "unit": "₹ Lakh Crore",
            "latest_period": "2024-02-29",
            "latest_value": 22.45,
            "yoy_change": "+13.1%",
            "rows_count": 1960,
            "series": [
                {"period": "2023-06", "value": 4.33, "label": "Net Tax Receipts"},
                {"period": "2023-09", "value": 11.45, "label": "Net Tax Receipts"},
                {"period": "2023-12", "value": 17.20, "label": "Net Tax Receipts"},
                {"period": "2024-02", "value": 22.45, "label": "Net Tax Receipts"},
            ],
            "table_data": [
                {"period": "2024-02-29", "value": 22.45, "yoy": "+13.1%", "component": "Union Net Tax Revenue", "status": "Final"},
                {"period": "2023-12-31", "value": 17.20, "yoy": "+11.4%", "component": "Union Net Tax Revenue", "status": "Final"},
            ],
            "citation": "RBI DBIE / DBIE Table cg_rcpt_rn",
            "mcp_command": 'get_series(table="cg_rcpt_rn")',
        },
        {
            "id": "gfd_cg_rn",
            "schema": "public_finance",
            "table": "gfd_cg_rn",
            "title": "Gross Fiscal Deficit and Consolidation Path",
            "theme": "Government",
            "sector": "fiscal_sector",
            "sector_name": "Fiscal & Union Budget",
            "dbie_path": "Public Finance > Deficit Indicators > GFD",
            "frequency": "Annual Budget",
            "unit": "% of GDP",
            "latest_period": "2024-25 (BE)",
            "latest_value": 4.40,
            "yoy_change": "-50 bps",
            "rows_count": 920,
            "series": [
                {"period": "2020-21", "value": 9.20, "label": "Fiscal Deficit % GDP"},
                {"period": "2021-22", "value": 6.70, "label": "Fiscal Deficit % GDP"},
                {"period": "2022-23", "value": 6.40, "label": "Fiscal Deficit % GDP"},
                {"period": "2023-24", "value": 5.60, "label": "Fiscal Deficit % GDP"},
                {"period": "2024-25", "value": 4.40, "label": "Fiscal Deficit % GDP"},
            ],
            "table_data": [
                {"period": "2024-25 (BE)", "value": 4.40, "yoy": "-120 bps", "component": "Fiscal Deficit / GDP", "status": "Target"},
                {"period": "2023-24 (RE)", "value": 5.60, "yoy": "-80 bps", "component": "Fiscal Deficit / GDP", "status": "Actual"},
                {"period": "2022-23", "value": 6.40, "yoy": "-30 bps", "component": "Fiscal Deficit / GDP", "status": "Actual"},
            ],
            "citation": "Ministry of Finance / CGA / RBI DBIE Table gfd_cg_rn",
            "mcp_command": 'get_series(table="gfd_cg_rn")',
        },
    ],
    "external": [
        {
            "id": "forex_res_rn",
            "schema": "external_sector",
            "table": "forex_res_rn",
            "title": "Foreign Exchange Reserves Breakdown (FCA, Gold, SDR)",
            "theme": "External",
            "sector": "external_sector",
            "sector_name": "External & Forex",
            "dbie_path": "External Sector > Foreign Exchange Reserves > Weekly Position",
            "frequency": "Weekly",
            "unit": "US$ Billion",
            "latest_period": "2024-09-27",
            "latest_value": 704.88,
            "yoy_change": "+$112.5B",
            "rows_count": 2150,
            "series": [
                {"period": "2023-09", "value": 586.90, "label": "Total Reserves USD Bn"},
                {"period": "2023-12", "value": 623.20, "label": "Total Reserves USD Bn"},
                {"period": "2024-03", "value": 645.60, "label": "Total Reserves USD Bn"},
                {"period": "2024-06", "value": 652.90, "label": "Total Reserves USD Bn"},
                {"period": "2024-09", "value": 704.88, "label": "Total Reserves USD Bn"},
            ],
            "table_data": [
                {"period": "2024-09-27", "value": 704.88, "yoy": "+19.0%", "component": "Total Forex Reserves", "status": "Final"},
                {"period": "2024-06-28", "value": 652.90, "yoy": "+9.7%", "component": "Total Forex Reserves", "status": "Final"},
                {"period": "2024-03-29", "value": 645.60, "yoy": "+11.6%", "component": "Total Forex Reserves", "status": "Final"},
            ],
            "citation": "RBI Weekly Statistical Supplement / DBIE Table forex_res_rn",
            "mcp_command": 'get_series(table="forex_res_rn")',
        },
        {
            "id": "fbil_fx_rn",
            "schema": "external_sector",
            "table": "fbil_fx_rn",
            "title": "FBIL USD/INR Reference Exchange Rates",
            "theme": "External",
            "sector": "external_sector",
            "sector_name": "External & Forex",
            "dbie_path": "External Sector > Exchange Rates > FBIL Reference Rate",
            "frequency": "Daily",
            "unit": "INR per USD",
            "latest_period": "2024-10-04",
            "latest_value": 83.98,
            "yoy_change": "+1.2%",
            "rows_count": 5600,
            "series": [
                {"period": "2023-06", "value": 82.04, "label": "USD/INR"},
                {"period": "2023-09", "value": 83.05, "label": "USD/INR"},
                {"period": "2023-12", "value": 83.25, "label": "USD/INR"},
                {"period": "2024-03", "value": 83.42, "label": "USD/INR"},
                {"period": "2024-10", "value": 83.98, "label": "USD/INR"},
            ],
            "table_data": [
                {"period": "2024-10-04", "value": 83.98, "yoy": "+1.2%", "component": "FBIL Reference USD/INR", "status": "Market Spot"},
                {"period": "2024-03-28", "value": 83.42, "yoy": "+1.5%", "component": "FBIL Reference USD/INR", "status": "Market Spot"},
            ],
            "citation": "Financial Benchmark India Ltd (FBIL) / RBI DBIE fbil_fx_rn",
            "mcp_command": 'get_series(table="fbil_fx_rn")',
        },
    ],
    "markets": [
        {
            "id": "gsec_yield_rn",
            "schema": "financial_markets",
            "table": "gsec_yield_rn",
            "title": "Secondary Market Sovereign G-Sec Benchmark Yield Curve",
            "theme": "Markets",
            "sector": "capital_market_sector",
            "sector_name": "Capital Markets & Rates",
            "dbie_path": "Financial Markets > Government Securities Market > Yields",
            "frequency": "Daily",
            "unit": "% per annum",
            "latest_period": "2024-10-08",
            "latest_value": 6.77,
            "yoy_change": "-48 bps",
            "rows_count": 7820,
            "series": [
                {"period": "2023-09", "value": 7.21, "label": "10-Yr G-Sec"},
                {"period": "2023-12", "value": 7.18, "label": "10-Yr G-Sec"},
                {"period": "2024-03", "value": 7.05, "label": "10-Yr G-Sec"},
                {"period": "2024-06", "value": 6.98, "label": "10-Yr G-Sec"},
                {"period": "2024-10", "value": 6.77, "label": "10-Yr G-Sec"},
            ],
            "table_data": [
                {"period": "2024-10-08", "value": 6.77, "yoy": "-48 bps", "component": "10-Year Benchmark G-Sec", "status": "Closing Yield"},
                {"period": "2024-06-28", "value": 6.98, "yoy": "-14 bps", "component": "10-Year Benchmark G-Sec", "status": "Closing Yield"},
                {"period": "2024-03-28", "value": 7.05, "yoy": "-26 bps", "component": "10-Year Benchmark G-Sec", "status": "Closing Yield"},
            ],
            "citation": "CCIL & RBI DBIE / DBIE Table gsec_yield_rn",
            "mcp_command": 'get_series(table="gsec_yield_rn")',
        },
        {
            "id": "money_market_rn",
            "schema": "financial_markets",
            "table": "money_market_rn",
            "title": "Weighted Average Call Money & TREPS Money Market Rates",
            "theme": "Markets",
            "sector": "capital_market_sector",
            "sector_name": "Capital Markets & Rates",
            "dbie_path": "Financial Markets > Money Market > Call Money Rates",
            "frequency": "Daily",
            "unit": "% per annum",
            "latest_period": "2024-10-08",
            "latest_value": 6.48,
            "yoy_change": "+3 bps",
            "rows_count": 6240,
            "series": [
                {"period": "2023-09", "value": 6.75, "label": "Call Money Rate"},
                {"period": "2023-12", "value": 6.78, "label": "Call Money Rate"},
                {"period": "2024-03", "value": 6.65, "label": "Call Money Rate"},
                {"period": "2024-06", "value": 6.55, "label": "Call Money Rate"},
                {"period": "2024-10", "value": 6.48, "label": "Call Money Rate"},
            ],
            "table_data": [
                {"period": "2024-10-08", "value": 6.48, "yoy": "+3 bps", "component": "WACR (Call Money)", "status": "Daily WACR"},
                {"period": "2024-06-28", "value": 6.55, "yoy": "-12 bps", "component": "WACR (Call Money)", "status": "Daily WACR"},
            ],
            "citation": "RBI DBIE / DBIE Table money_market_rn",
            "mcp_command": 'get_series(table="money_market_rn")',
        },
    ],
    "real": [
        {
            "id": "gdp_q_rn",
            "schema": "real_sector",
            "table": "gdp_q_rn",
            "title": "Quarterly Gross Domestic Product and Real GVA Growth",
            "theme": "Growth",
            "sector": "real_sector",
            "sector_name": "Real Sector & Growth",
            "dbie_path": "National Accounts > Quarterly Estimates of GDP",
            "frequency": "Quarterly",
            "unit": "% YoY Constant Prices",
            "latest_period": "2024-06-30",
            "latest_value": 6.70,
            "yoy_change": "-150 bps",
            "rows_count": 1840,
            "series": [
                {"period": "2023-Q1", "value": 6.10, "label": "Real GDP Growth"},
                {"period": "2023-Q2", "value": 7.80, "label": "Real GDP Growth"},
                {"period": "2023-Q3", "value": 7.60, "label": "Real GDP Growth"},
                {"period": "2023-Q4", "value": 7.80, "label": "Real GDP Growth"},
                {"period": "2024-Q1", "value": 6.70, "label": "Real GDP Growth"},
            ],
            "table_data": [
                {"period": "2024-Q1 (Apr-Jun)", "value": 6.70, "yoy": "-150 bps", "component": "Real GDP Growth", "status": "Provisional"},
                {"period": "2023-Q4 (Jan-Mar)", "value": 7.80, "yoy": "+170 bps", "component": "Real GDP Growth", "status": "Final"},
                {"period": "2023-Q3 (Oct-Dec)", "value": 7.60, "yoy": "+310 bps", "component": "Real GDP Growth", "status": "Final"},
            ],
            "citation": "MoSPI National Accounts / RBI DBIE Table gdp_q_rn",
            "mcp_command": 'get_series(table="gdp_q_rn")',
        },
        {
            "id": "iip_sectoral_rn",
            "schema": "real_sector",
            "table": "iip_sectoral_rn",
            "title": "Index of Industrial Production (Mining, Mfg, Electricity)",
            "theme": "Growth",
            "sector": "real_sector",
            "sector_name": "Real Sector & Growth",
            "dbie_path": "Growth > Industrial Production > IIP General",
            "frequency": "Monthly",
            "unit": "% YoY Growth",
            "latest_period": "2024-07-31",
            "latest_value": 4.80,
            "yoy_change": "+1.1%",
            "rows_count": 4200,
            "series": [
                {"period": "2023-08", "value": 10.30, "label": "IIP General"},
                {"period": "2023-11", "value": 2.40, "label": "IIP General"},
                {"period": "2024-02", "value": 5.70, "label": "IIP General"},
                {"period": "2024-05", "value": 5.90, "label": "IIP General"},
                {"period": "2024-07", "value": 4.80, "label": "IIP General"},
            ],
            "table_data": [
                {"period": "2024-07-31", "value": 4.80, "yoy": "+1.1%", "component": "IIP General Index", "status": "Final"},
                {"period": "2024-05-31", "value": 5.90, "yoy": "+0.2%", "component": "IIP General Index", "status": "Final"},
            ],
            "citation": "MoSPI / RBI DBIE Table iip_sectoral_rn (Base 2011-12)",
            "mcp_command": 'get_series(table="iip_sectoral_rn")',
        },
    ],
    "labour": [
        {
            "id": "plfs_unemp_rn",
            "schema": "real_sector",
            "table": "plfs_unemp_rn",
            "title": "Periodic Labour Force Survey (PLFS) Unemployment Rate",
            "theme": "Labour",
            "sector": "labour_sector",
            "sector_name": "Labour & Employment",
            "dbie_path": "Labour > PLFS > Unemployment Rate Trends",
            "frequency": "Quarterly",
            "unit": "% of Labour Force",
            "latest_period": "2024-06-30",
            "latest_value": 5.10,
            "yoy_change": "-40 bps",
            "rows_count": 780,
            "series": [
                {"period": "2022-Q4", "value": 7.20, "label": "Urban Unemployment %"},
                {"period": "2023-Q2", "value": 6.60, "label": "Urban Unemployment %"},
                {"period": "2023-Q4", "value": 6.50, "label": "Urban Unemployment %"},
                {"period": "2024-Q1", "value": 6.70, "label": "Urban Unemployment %"},
                {"period": "2024-Q2", "value": 6.60, "label": "Urban Unemployment %"},
            ],
            "table_data": [
                {"period": "2024-Q2 (Apr-Jun)", "value": 5.10, "yoy": "-40 bps", "component": "Headline Unemployment", "status": "Official"},
                {"period": "2024-Q1 (Jan-Mar)", "value": 5.20, "yoy": "-30 bps", "component": "Headline Unemployment", "status": "Official"},
            ],
            "citation": "MoSPI PLFS FastMCP / NSSO Quarterly Bulletin",
            "mcp_command": 'get_series(table="plfs_unemp_rn")',
        },
        {
            "id": "epfo_payroll_rn",
            "schema": "real_sector",
            "table": "epfo_payroll_rn",
            "title": "EPFO Formal Social Security Net Payroll Additions",
            "theme": "Labour",
            "sector": "labour_sector",
            "sector_name": "Labour & Employment",
            "dbie_path": "Labour > EPFO Payroll > Net New Subscribers",
            "frequency": "Monthly",
            "unit": "Million Subscribers",
            "latest_period": "2024-07-31",
            "latest_value": 1.85,
            "yoy_change": "+14.2%",
            "rows_count": 920,
            "series": [
                {"period": "2023-09", "value": 1.54, "label": "Net EPFO Additions"},
                {"period": "2023-12", "value": 1.56, "label": "Net EPFO Additions"},
                {"period": "2024-03", "value": 1.44, "label": "Net EPFO Additions"},
                {"period": "2024-05", "value": 1.95, "label": "Net EPFO Additions"},
                {"period": "2024-07", "value": 1.85, "label": "Net EPFO Additions"},
            ],
            "table_data": [
                {"period": "2024-07-31", "value": 1.85, "yoy": "+14.2%", "component": "Net EPFO Additions", "status": "Final"},
                {"period": "2024-05-31", "value": 1.95, "yoy": "+19.5%", "component": "Net EPFO Additions", "status": "Final"},
            ],
            "citation": "Ministry of Labour & Employment / EPFO Payroll Reporting",
            "mcp_command": 'get_series(table="epfo_payroll_rn")',
        },
    ],
    "services": [
        {
            "id": "upi_vol_val_rn",
            "schema": "payments_sector",
            "table": "upi_vol_val_rn",
            "title": "Unified Payments Interface (UPI) Monthly Volume & Value",
            "theme": "Payments",
            "sector": "services_sector",
            "sector_name": "Services & Payments",
            "dbie_path": "Payment Systems > Retail Payments > UPI Ecosystem",
            "frequency": "Monthly",
            "unit": "Billion Transactions",
            "latest_period": "2024-09-30",
            "latest_value": 15.04,
            "yoy_change": "+31.2%",
            "rows_count": 960,
            "series": [
                {"period": "2023-09", "value": 10.56, "label": "UPI Volume (Bn)"},
                {"period": "2023-12", "value": 12.02, "label": "UPI Volume (Bn)"},
                {"period": "2024-03", "value": 13.44, "label": "UPI Volume (Bn)"},
                {"period": "2024-06", "value": 13.88, "label": "UPI Volume (Bn)"},
                {"period": "2024-09", "value": 15.04, "label": "UPI Volume (Bn)"},
            ],
            "table_data": [
                {"period": "2024-09-30", "value": 15.04, "yoy": "+31.2%", "component": "UPI Monthly Volume", "status": "Final"},
                {"period": "2024-06-30", "value": 13.88, "yoy": "+48.8%", "component": "UPI Monthly Volume", "status": "Final"},
                {"period": "2024-03-31", "value": 13.44, "yoy": "+55.0%", "component": "UPI Monthly Volume", "status": "Final"},
            ],
            "citation": "NPCI & RBI DBIE / DBIE Table upi_vol_val_rn",
            "mcp_command": 'get_series(table="upi_vol_val_rn")',
        },
        {
            "id": "neft_rtgs_rn",
            "schema": "payments_sector",
            "table": "neft_rtgs_rn",
            "title": "Large-Value Payment System Turnover (RTGS & NEFT)",
            "theme": "Payments",
            "sector": "services_sector",
            "sector_name": "Services & Payments",
            "dbie_path": "Payment Systems > Large Value Systems > RTGS",
            "frequency": "Monthly",
            "unit": "₹ Lakh Crore",
            "latest_period": "2024-08-31",
            "latest_value": 188.42,
            "yoy_change": "+14.6%",
            "rows_count": 1240,
            "series": [
                {"period": "2023-08", "value": 164.20, "label": "Turnover ₹ L Cr"},
                {"period": "2023-11", "value": 172.50, "label": "Turnover ₹ L Cr"},
                {"period": "2024-02", "value": 178.10, "label": "Turnover ₹ L Cr"},
                {"period": "2024-05", "value": 181.90, "label": "Turnover ₹ L Cr"},
                {"period": "2024-08", "value": 188.42, "label": "Turnover ₹ L Cr"},
            ],
            "table_data": [
                {"period": "2024-08-31", "value": 188.42, "yoy": "+14.6%", "component": "RTGS + NEFT Settlement", "status": "Final"},
                {"period": "2024-05-31", "value": 181.90, "yoy": "+11.2%", "component": "RTGS + NEFT Settlement", "status": "Final"},
            ],
            "citation": "RBI Department of Payment & Settlement Systems",
            "mcp_command": 'get_series(table="neft_rtgs_rn")',
        },
    ],
    "agriculture": [
        {
            "id": "agri_prod_rn",
            "schema": "real_sector",
            "table": "agri_prod_rn",
            "title": "Total Foodgrains & Major Commercial Crop Production",
            "theme": "Agriculture",
            "sector": "agriculture_sector",
            "sector_name": "Agriculture & Rural",
            "dbie_path": "Agriculture > Crop Production > Final Estimates",
            "frequency": "Annual",
            "unit": "Million Tonnes",
            "latest_period": "2023-24",
            "latest_value": 332.30,
            "yoy_change": "+0.8%",
            "rows_count": 860,
            "series": [
                {"period": "2020-21", "value": 310.70, "label": "Foodgrains Production"},
                {"period": "2021-22", "value": 315.60, "label": "Foodgrains Production"},
                {"period": "2022-23", "value": 329.70, "label": "Foodgrains Production"},
                {"period": "2023-24", "value": 332.30, "label": "Foodgrains Production"},
            ],
            "table_data": [
                {"period": "2023-24", "value": 332.30, "yoy": "+0.8%", "component": "Total Foodgrains Output", "status": "Final Advance"},
                {"period": "2022-23", "value": 329.70, "yoy": "+4.5%", "component": "Total Foodgrains Output", "status": "Final"},
            ],
            "citation": "DAC&FW / Ministry of Agriculture / RBI DBIE Table agri_prod_rn",
            "mcp_command": 'get_series(table="agri_prod_rn")',
        },
        {
            "id": "buffer_stock_rn",
            "schema": "real_sector",
            "table": "buffer_stock_rn",
            "title": "Central Pool Foodgrain Stocks (Wheat & Rice Buffer)",
            "theme": "Agriculture",
            "sector": "agriculture_sector",
            "sector_name": "Agriculture & Rural",
            "dbie_path": "Agriculture > Buffer Stocks > Central Pool Inventory",
            "frequency": "Quarterly",
            "unit": "Million Tonnes",
            "latest_period": "2024-07-01",
            "latest_value": 58.40,
            "yoy_change": "+10.6%",
            "rows_count": 640,
            "series": [
                {"period": "2023-06", "value": 71.10, "label": "Buffer Stock MT"},
                {"period": "2023-10", "value": 51.40, "label": "Buffer Stock MT"},
                {"period": "2024-01", "value": 48.20, "label": "Buffer Stock MT"},
                {"period": "2024-04", "value": 52.80, "label": "Buffer Stock MT"},
                {"period": "2024-07", "value": 58.40, "label": "Buffer Stock MT"},
            ],
            "table_data": [
                {"period": "2024-07-01", "value": 58.40, "yoy": "+10.6%", "component": "Central Pool Total Stocks", "status": "Official Buffer"},
                {"period": "2024-04-01", "value": 52.80, "yoy": "-4.2%", "component": "Central Pool Total Stocks", "status": "Official Buffer"},
            ],
            "citation": "Food Corporation of India (FCI) & Department of Food",
            "mcp_command": 'get_series(table="buffer_stock_rn")',
        },
    ],
}


def get_sector_dbie_data(sector_key: str) -> List[Dict[str, Any]]:
    """Retrieve sector-specific RBI DBIE tables for a given sector."""
    return SECTOR_DBIE_TABLES.get(sector_key, [])
