"""Re-exports standard A2A models and interfaces from core.protocols.a2a."""
from core.protocols.a2a import (
    A2AArtifact,
    A2AMessage,
    A2AMessagePart,
    AgentCapabilities,
    AgentCard,
    AgentExecutor,
    AgentRegistry,
    AgentSkill,
    EventQueue,
    RequestContext,
    TaskArtifactUpdateEvent,
    TaskManager,
    TaskRequest,
    TaskResponse,
    TaskState,
    TaskStatus,
    TaskStatusUpdateEvent,
    registry,
    task_event_stream,
)

__all__ = [
    "A2AArtifact",
    "A2AMessage",
    "A2AMessagePart",
    "AgentCapabilities",
    "AgentCard",
    "AgentExecutor",
    "AgentRegistry",
    "AgentSkill",
    "EventQueue",
    "RequestContext",
    "TaskArtifactUpdateEvent",
    "TaskManager",
    "TaskRequest",
    "TaskResponse",
    "TaskState",
    "TaskStatus",
    "TaskStatusUpdateEvent",
    "registry",
    "task_event_stream",
]
